export const macroLocators = {
    macroHome: '//android.view.ViewGroup[@resource-id="com.arlosoft.macrodroid:id/editMacroContainer"]',
    addtriggerButton: '//android.widget.ImageButton[@content-desc="Add Trigger"]',
    macrotriggerwithName: '//androidx.recyclerview.widget.RecyclerView[@resource-id="com.arlosoft.macrodroid:id/triggersList"]//android.widget.TextView[@resource-id="com.arlosoft.macrodroid:id/macro_edit_entry_name"]',
    macrotriggerwithDetails: '//androidx.recyclerview.widget.RecyclerView[@resource-id="com.arlosoft.macrodroid:id/triggersList"]//android.widget.TextView[@resource-id="com.arlosoft.macrodroid:id/macro_edit_entry_detail"]',
    addactionButton: '//android.widget.ImageButton[@content-desc="Add Action"]',
    macroactionwithName: '//androidx.recyclerview.widget.RecyclerView[@resource-id="com.arlosoft.macrodroid:id/actionsList"]//android.widget.TextView[@resource-id="com.arlosoft.macrodroid:id/macro_edit_entry_name"]',
    macroactionwithDetails: '//androidx.recyclerview.widget.RecyclerView[@resource-id="com.arlosoft.macrodroid:id/actionsList"]//android.widget.TextView[@resource-id="com.arlosoft.macrodroid:id/macro_edit_entry_detail"]',
    addconstraintsButton: '//android.widget.ImageButton[@content-desc="Add constraint"]',
    macroconstraintswithName: '//androidx.recyclerview.widget.RecyclerView[@resource-id="com.arlosoft.macrodroid:id/constraintsList"]//android.widget.TextView[@resource-id="com.arlosoft.macrodroid:id/macro_edit_entry_name"]',
    localVarButton: '//android.widget.TextView[@resource-id="com.arlosoft.macrodroid:id/localVarsLabel"]',
    addlocalVarButton: '//android.widget.ImageButton[@resource-id="com.arlosoft.macrodroid:id/addVariableButton"]',
    createNewVarTitlePopup: '//android.widget.TextView[@text="Create New Variable"]',
    localVarInputField: '//android.widget.EditText[@resource-id="com.arlosoft.macrodroid:id/variable_new_variable_dialog_name"]',
    localVarTypeSelect: '//android.widget.Spinner[@resource-id="com.arlosoft.macrodroid:id/variable_new_variable_type_spinner"]',
    localVarIntegerSelect: '//android.widget.CheckedTextView[@resource-id="android:id/text1" and @text="Integer"]',
    okButton: '//android.widget.Button[@resource-id="com.arlosoft.macrodroid:id/okButton"]',
    cancelButton: '//android.widget.Button[@resource-id="com.arlosoft.macrodroid:id/cancelButton"]',
    localVarwithName: '//androidx.recyclerview.widget.RecyclerView[@resource-id="com.arlosoft.macrodroid:id/localVarsList"]//android.widget.TextView[@resource-id="com.arlosoft.macrodroid:id/macro_edit_entry_name"]',

};